version: "3.9"
services:
  hexapokernet-webapi:
    build: .
    ports:
      - "8080:80"
    environment:
      Logging__LogLevel__Default: Debug
    depends_on:
      - broker

  test-web-api:
    build: ./tests-acceptance/web-api
    depends_on:
      - hexapokernet-webapi
    environment:
      APP_HOST: hexapokernet-webapi
      APP_PORT: 80
